import type { Metadata } from "next";
import "./globals.css";
import Header from './components/Header';
import { AuthProvider } from './context/AuthContext';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

export const metadata: Metadata = {
  title: "Missing Activist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-[#545454] text-black flex justify-center">
        <div className="w-full max-w-md relative bg-white shadow-md">
          <AuthProvider>
          <ToastContainer 
            position="top-center"
            autoClose={2000}
            pauseOnHover={true}
            closeOnClick={true}
            draggable={true} />
            <Header />
            <main>{children}</main>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
